apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAAm7qS/TBuz5PTzI8HDgLapjW2vrkXOuxyQPLX45nU0oxYLP31mcea0lM3t99Abr88Wr/opGcDgoTVrjx1tXh4Vb8/PLr7Vu3vd1/9FldvXbzStvDDQ14Wsdz8KhKJj9o0gvDMJUMwDifInhwfkHnS8L8lopNlEtUWF+3E05/soZ4v3uJLiHXgSl5aSx6zPh7ZseIcNG4SXjcVdIluuq4yc+QptRjB0odrsanoziEcKxnauAi/j47+ZPgWsJpgb+HXcK5LjzTvYDNiOLNT9ziy1NSPLDbl2k/KFnwagxdlv+BXrUNc1l5lVN7yrm3bjibubPTksFKji3TqurBQCeSwd6XnQxJRT69+nN6AoJczHe6ci+hrYdaxIoLkdwtKyiNEeyd2ADovaNIqwU0RWcvguCr+IM+98OHbZPMB+mUGecaras+JMGpAFa7Nd3FlRLpg7DCrQqr2zhoOCP++Tm/ZnqGdKHxh6KOn3OVx3Xjwy8mk4aGHs/BFdYzBBX6i4oi4BTCmuTijbpPeXGrp8UjHl6WhDhT8LQmhP/b9/8yQzfsILLHCyuv7ZRHiCq0LK2b8OfLLMXCB3xrW4Ky+70ZjHK6n312+SwNJj4SkvwxAi0GEMmB75HH6KPlXOQJXUkrRJ17BZAeDPRxRwp0vN+jhuMO33FJjwGRMjtRJZ9cUrxrODUZggWGt9da/IswXH0Ud6ZgADFuqIOZ6Bd0++B5Xr8sjiQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
