apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCIsPdLkcN+vfdGf1ZOczqximrso/4H4q5xycn2n7d1hcWUqeT2T1Y87XScrRYV1hUQeamEeiR7NculxPRdm/eQ+Cd0pf4r4kcf78yq8CghyogoPBcY2g7etpb9dp2Upis69EgOx1Mt0YYFB8mtkVG2acVAQtuRvXY4gR1OQ8+3+3OZrD6tUrNJjtM2/w0zz2w2f8v1qVqxfkuj9GUS2GCqV0Yk9CCtTiAeiFWAWYQBS2+hooA/TLp802eU3Le46aqi4x5CXChNNuVJHC55TEhSnfr+pcJggFPf8sr4imbjgwaDhTBhliMUY0fqpPAdQb1cLPZAVT1FVXyYN/lqutgUnBSxvNUcK+lQPOjxAKoPbxIym6V05J9Ek0PyF8V+SXKs109Sdz9+6fIakPPZEJMqc/xuUEdKGIepFZMv7Nva7Kwx/FXlDmvawiwMb0HqY5GEtYDOeICgDaTaIlYjF/GtbInYiV57AiGvivjBf88WhpFeuno2XUsEDVXotif5fdyn3snNXSul6bfH3Huj0HLUR+FfXyR1F/TO2oi1C8K0T5IkAlcyyumyAlky2cxumGbDrUqI/nPItsMBgbvH1FI8mLxrlwFZphOJi2Hz+MCkxhYgyPoQxpK8nUBCEK54IqUxtXwQzFUFpCogZ9YRX259+DMr6UoknWhTTr4Ms8YRhk8Ylaq9QnNXmvZLTBeiu9vh9rPuTnT1bOdJXKq5PyQ0vBTQgQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
